#!/usr/bin/env bash
# Bash script that will display information about subdomains.
print_info ()
{
    dom="$1"
    subd="$2"
    subs="www lb-01 web-01 web-02"
    if [ "$#" == 2 ]; then
	dig "$subd.$dom" | grep -A1 'ANSWER SECTION: ' | tail -n1 | awk -v subd=$2 -v rec=$4 -v ip=$5\
        '{print "The subdomain $subd is a $rec record and points to $ip"}'
    elif [ "$#" == 1 ]; then
	for i in "${subs[@]}"; do
	    dig "${subs[i]}.$dom" | grep -A1 'ANSWER SECTION: ' | tail -n1 | awk -v subd=$2 -v rec=$4 -v ip=$5\
            '{print "The subdomain $subd is a $rec record and points to $ip"}'
	done
    fi
}
print_info "$1" "$2"
