#!/usr/bin/env bash
# Bash script that redirects to another page
apt-get -y update
apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i "37i \\\tlocation /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \n\t}\n" /etc/nginx/sites-available/default
service nginx restart
