#!/usr/bin/env bash
# Bash script that redirects to another page
apt-get -y update
apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i "37i location /redirect_me {\n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; n}n" /etc/nginx/sites-available/default
service nginx restart
