#!/usr/bin/env bash
# Automatizing the nginx configuration
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i "15i \\\tadd_header X-Served-By 1552-web-02;" /etc/nginx/nginx.conf
sudo service nginx restart
