#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times but on the 9th prints Hi
i="0"
while [ $i -lt 10 ]
do
    if [ $i -eq 8 ]; then
	echo "Holberton School"
	echo "Hi"
    else
	echo "Holberton School"
    fi
    i=$((i+1))
done
