#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times but on the 9th prints Hi
i="0"
while [ $i -lt 10 ]
do
    if [ $i -eq 5 ]; then
	echo "bad luck"
    elif [ $i -eq 9 ]; then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    i=$((i+1))
done
