#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times but on the 9th prints Hi
i="1"
while [ $i -le 20 ]
do
    echo "$i"
    case $i in
	4) echo "bad luck from China"
        ;;
	9) echo "bad luck from Japan"
	;;
	17) echo "bad luck from Italy"
	;;
     esac
    i=$((i+1))
done
