#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times but on the 9th prints Hi
h="0"
while [ $h -le 12 ]
do
    echo "Hour: $h"
    m="1"
    while [ $m -lt 60 ]
    do
	echo "$m"
	m=$((m+1))
    done
    h=$((h+1))
done
