#!/usr/bin/env bash
#  a Bash script that configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
cp /etc/hosts ~/hosts.new
sed -i s/^/127.0.0.2 localhost$/ ~/hosts.new
sed  -i s/^/8.8.8.8 facebook$/ ~/hosts.new
cp -f ~/hosts.new /etc/hosts
